services:
  ms-business:
    build:
      context: .
      args:
        BUILDPLATFORM: linux/arm64
    platform: linux/arm64
    ports:
      - "8090:8090"
    env_file:
      - .env
    networks:
      - gateway-network

networks:
  gateway-network:
    external: true